# Generated by Django 5.2.3 on 2025-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=100, null=True)),
                ('cpu_percent', models.FloatField(blank=True, db_column='CPU_percent', null=True)),
                ('time', models.DateTimeField(blank=True, db_column='TIME', null=True)),
                ('ram_percent', models.FloatField(blank=True, db_column='RAM_percent', null=True)),
                ('mysql_ram_percent', models.FloatField(blank=True, db_column='MySQL_RAM_percent', null=True)),
                ('load_average', models.FloatField(blank=True, db_column='Load_Average', null=True)),
                ('uptime_mysql', models.BigIntegerField(blank=True, db_column='Uptime_mysql', null=True)),
                ('uptime_linux', models.BigIntegerField(blank=True, db_column='Uptime_Linux', null=True)),
                ('packet_loss', models.IntegerField(blank=True, db_column='Packet_Loss', null=True)),
            ],
            options={
                'db_table': 'Stats',
                'managed': False,
            },
        ),
    ]
